[package]
authors = ["Daniel García Moreno <danigm@wadobo.com>"]
description = """
Library to support the reading of epub files.
"""
documentation = "https://danigm.github.io/epub-rs-doc/epub/index.html"
exclude = ["test.epub"]
keywords = [
    "epub",
    "ebook",
]
license = "GPL-3.0"
name = "epub"
repository = "https://github.com/danigm/epub-rs.git"
version = "1.1.0"

[dependencies]
failure = "0.1.1"
regex = "0.2.3"
xml-rs = "0.7.0"
zip = "0.2.6"
